<Specification>
  <!--

  ENTITY - the parts common to all entities.

  -->
  <Interface Name="Entity">
    <Method Signature="codePairs(version AcadVersion) (pairs []CodePair)" />
    <Method Signature="minVersion() AcadVersion" />
    <Method Signature="maxVersion() AcadVersion" />
    <Method Signature="tryApplyCodePair(pair CodePair)" />
    <Method Signature="typeString() string" />
    <Method Signature="pointers() (pointers []*pointer)" />
    <Field Name="Handle" Code="5" Type="Handle" DefaultValue="0" ReadConverter="handleFromString(%v)" WriteConverter="stringFromHandle(%v)" DisableWritingDefault="true" />
    <Pointer Name="Owner" Code="330" Type="DrawingItem" />
    <Field Name="IsInPaperSpace" Code="67" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" DisableWritingDefault="true" MinVersion="R12" />
    <Field Name="Layer" Code="8" Type="string" DefaultValue='"0"' WriteConverter='defaultIfEmpty(%v, "0")' />
    <Field Name="LineTypeName" Code="6" Type="string" DefaultValue='"BYLAYER"' DisableWritingDefault="true" />
    <Field Name="Elevation" Code="38" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" MaxVersion="R12" />
    <Field Name="MaterialHandle" Code="347" Type="string" DefaultValue='"BYLAYER"' DisableWritingDefault="true" MinVersion="R2007" />
    <Field Name="Color" Code="62" Type="Color" DefaultValue="ByLayer()" ReadConverter="Color(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="LineWeight" Code="370" Type="LineWeight" DefaultValue="NewLineWeightStandard()" ReadConverter="LineWeight(%v)" WriteConverter="int16(%v)" MinVersion="R2000" />
    <Field Name="LineTypeScale" Code="48" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" MinVersion="R13" />
    <Field Name="IsVisible" Code="60" Type="bool" DefaultValue="true" ReadConverter="!boolFromShort(%v)" WriteConverter="shortFromBool(!%v)" DisableWritingDefault="true" MinVersion="R13" />
    <Field Name="ImageByteCount" Code="92" Type="int" DefaultValue="0" DisableWritingDefault="true" MinVersion="R2000" />
    <Field Name="PreviewImageData" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" MinVersion="R2000" />
    <Field Name="Color24Bit" Code="420" Type="int" DefaultValue="0" DisableWritingDefault="true" MinVersion="R2004" />
    <Field Name="ColorName" Code="430" Type="string" DefaultValue='""' MinVersion="R2004" />
    <Field Name="Transparency" Code="440" Type="int" DefaultValue="0" MinVersion="R2004" />
    <Pointer Name="PlotStyle" Code="390" Type="DrawingItem" MinVersion="R2007" />
    <Field Name="ShadowMode" Code="284" Type="ShadowMode" DefaultValue="ShadowModeCastsAndReceivesShadows" ReadConverter="ShadowMode(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <WriteOrder>
      <WriteField Field="Handle" />
      <WriteExtensionData />
      <WritePointer Pointer="Owner" />
      <WriteSpecificValue Code="100" Value='"AcDbEntity"' MinVersion="R13" />
      <WriteField Field="IsInPaperSpace" />
      <WriteField Field="Layer" />
      <WriteField Field="LineTypeName" />
      <WriteField Field="Elevation" />
      <WriteField Field="MaterialHandle" />
      <WriteField Field="Color" />
      <WriteField Field="LineWeight" />
      <WriteField Field="LineTypeScale" />
      <WriteField Field="IsVisible" />
      <WriteField Field="ImageByteCount" />
      <WriteField Field="PreviewImageData" />
      <WriteField Field="Color24Bit" />
      <WriteField Field="ColorName" />
      <WriteField Field="Transparency" />
      <WritePointer Pointer="PlotStyle" />
      <WriteField Field="ShadowMode" />
    </WriteOrder>
  </Interface>
  <!--

  3DFACE

  -->
  <Entity Name="Face" SubclassMarker="AcDbFace" TypeString="3DFACE">
    <Field Name="FirstCorner" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="SecondCorner" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ThirdCorner" Code="12" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="12,22,32" />
    <Field Name="FourthCorner" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="EdgeFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="FirstEdgeInvisible" Mask="1" />
      <Flag Name="SecondEdgeInvisible" Mask="2" />
      <Flag Name="ThirdEdgeInvisible" Mask="4" />
      <Flag Name="FourthEdgeInvisible" Mask="8" />
    </Field>
  </Entity>
  <!--

  3DSOLID

  -->
  <Entity Name="Solid3D" SubclassMarker="AcDbModelerGeometry" TypeString="3DSOLID" MinVersion="R13">
    <Field Name="FormatVersionNumber" Code="70" Type="int16" DefaultValue="1" />
    <Field Name="CustomData" Code="1" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="CustomData2" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Pointer Name="HistoryObject" Code="350" Type="DrawingItem" MinVersion="R2007" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbModelerGeometry"' />
      <WriteField Field="FormatVersionNumber" />
      <WriteField Field="CustomData" />
      <WriteField Field="CustomData2" />
      <WriteSpecificValue Code="100" Value='"AcDb3dSolid"' MinVersion="R2007" />
      <WritePointer Pointer="HistoryObject" />
    </WriteOrder>
  </Entity>
  <!--

  ACAD_PROXY_ENTITY

  -->
  <Entity Name="ProxyEntity" SubclassMarker="AcDbProxyEntity" TypeString="ACAD_PROXY_ENTITY" MinVersion="R14" GenerateReader="false">
    <Field Name="readingGraphicsData" Type="bool" DefaultValue="true" />
    <Field Name="ProxyEntityClassId" Code="90" Type="int" DefaultValue="498" />
    <Field Name="ApplicationEntityClassId" Code="91" Type="int" DefaultValue="500" />
    <Field Name="GraphicsData" Type="[]byte" DefaultValue="[]byte{}" />
    <Field Name="graphicsDataSize" Code="92" Type="int" DefaultValue="0" />
    <Field Name="graphicsDataString" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="EntityData" Type="[]byte" DefaultValue="[]byte{}" />
    <Field Name="entityDataSize" Code="93" Type="int" DefaultValue="0" />
    <Field Name="entityDataString" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID1" Code="330" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID2" Code="340" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID3" Code="350" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="ObjectID4" Code="360" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="Terminator" Code="94" Type="int" DefaultValue="0" />
    <Field Name="objectDrawingFormat" Code="95" Type="uint" DefaultValue="0" ReadConverter="uint(%v)" WriteConverter="int(%v)" MinVersion="R2000" />
    <Field Name="OriginalDataFormatIsDxf" Code="70" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2000" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbProxyEntity"' />
      <WriteField Field="ProxyEntityClassId" />
      <WriteField Field="ApplicationEntityClassId" />
      <WriteSpecificValue Code="92" Value="len(this.GraphicsData)" />
      <WriteField Field="graphicsDataString" />
      <WriteSpecificValue Code="93" Value="len(this.EntityData)" />
      <WriteField Field="entityDataString" />
      <WriteField Field="ObjectID1" />
      <WriteField Field="ObjectID2" />
      <WriteField Field="ObjectID3" />
      <WriteField Field="ObjectID4" />
      <WriteField Field="Terminator" />
      <WriteField Field="objectDrawingFormat" />
      <WriteField Field="OriginalDataFormatIsDxf" />
    </WriteOrder>
  </Entity>
  <!--

  ARC

  -->
  <Entity Name="Arc" SubclassMarker="AcDbArc" TypeString="ARC">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Center" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Radius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="StartAngle" Code="50" Type="float64" DefaultValue="0.0" Comment="Arc start angle in degrees" />
    <Field Name="EndAngle" Code="51" Type="float64" DefaultValue="360.0" Comment="Arc end angle in degrees" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbCircle"' />
      <WriteField Field="Thickness" />
      <WriteField Field="Center" />
      <WriteField Field="Radius" />
      <WriteField Field="Normal" />
      <WriteSpecificValue Code="100" Value='"AcDbArc"' />
      <WriteField Field="StartAngle" />
      <WriteField Field="EndAngle" />
    </WriteOrder>
  </Entity>
  <!--

  ARCALIGNEDTEXT

  -->
  <Entity Name="ArcAlignedText" SubclassMarker="AcDbArcAlignedText" TypeString="ARCALIGNEDTEXT" MinVersion="R2000" MaxVersion="R2000">
    <Field Name="Text" Code="1" Type="string" DefaultValue='""' />
    <Field Name="FontName" Code="2" Type="string" DefaultValue='""' />
    <Field Name="BigfontName" Code="3" Type="string" DefaultValue='""' />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='""' />
    <Field Name="CenterPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="ArcRadius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="WidthFactor" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="TextHeight" Code="42" Type="float64" DefaultValue="0.0" />
    <Field Name="CharacterSpacing" Code="43" Type="float64" DefaultValue="0.0" />
    <Field Name="OffsetFromArc" Code="44" Type="float64" DefaultValue="0.0" />
    <Field Name="RightOffset" Code="45" Type="float64" DefaultValue="0.0" />
    <Field Name="LeftOffset" Code="46" Type="float64" DefaultValue="0.0" />
    <Field Name="StartAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="EndAngle" Code="51" Type="float64" DefaultValue="0.0" />
    <Field Name="IsCharacterOrderReversed" Code="70" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="DirectionFlag" Code="71" Type="int16" DefaultValue="0" />
    <Field Name="AlignmentFlag" Code="72" Type="int16" DefaultValue="0" />
    <Field Name="SideFlag" Code="73" Type="int16" DefaultValue="0" />
    <Field Name="IsBold" Code="74" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsItalic" Code="75" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsUnderline" Code="76" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="CharacterSetValue" Code="77" Type="int16" DefaultValue="0" />
    <Field Name="PitchAndFamilyValue" Code="78" Type="int16" DefaultValue="0" />
    <Field Name="FontType" Code="79" Type="FontType" DefaultValue="FontTypeTTF" ReadConverter="FontType(%v)" WriteConverter="int16(%v)" />
    <Field Name="ColorIndex" Code="90" Type="int" DefaultValue="0" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="WizardFlag" Code="280" Type="int16" DefaultValue="0" />
  </Entity>
  <!--

  ATTDEF

  -->
  <Entity Name="AttributeDefinition" SubclassMarker="nil" TypeString="ATTDEF" GenerateReader="false">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="TextHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Value" Code="1" Type="string" DefaultValue='""' />
    <Field Name="Rotation" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RelativeXScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ObliqueAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Field>
    <Field Name="HorizontalTextJustification" Code="72" Type="HorizontalTextJustification" DefaultValue="HorizontalTextJustificationLeft" ReadConverter="HorizontalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SecondAlignmentPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="Version" Code="280" Type="Version" DefaultValue="VersionR2010" ReadConverter="Version(%v)" WriteConverter="int16(%v)" MinVersion="R2010" />
    <Field Name="Prompt" Code="3" Type="string" DefaultValue='""' />
    <Field Name="TextTag" Code="2" Type="string" DefaultValue='""' />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsInvisible" Mask="1" />
      <Flag Name="IsConstant" Mask="2" />
      <Flag Name="IsInputVerificationRequired" Mask="4" />
      <Flag Name="IsAttributePresent" Mask="8" />
    </Field>
    <Field Name="FieldLength" Code="73" Type="int16" DefaultValue="0" DisableWritingDefault="true" />
    <Field Name="VerticalTextJustification" Code="74" Type="VerticalTextJustification" DefaultValue="VerticalTextJustificationBaseline" ReadConverter="VerticalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" MinVersion="R12" />
    <Field Name="IsLockedInBlock" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="KeepDuplicateRecords" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="MTextFlag" Code="70" Type="MTextFlag" DefaultValue="MTextFlagMultilineAttribute" ReadConverter="MTextFlag(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="IsReallyLocked" Code="70" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="secondaryAttributeHandlesCount" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="SecondaryAttributeHandles" Code="340" Type="string" DefaultValue="[]string{}" AllowMultiples="true" MinVersion="R2007" />
    <Field Name="AlignmentPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" MinVersion="R2007" />
    <Field Name="AnnotationScale" Code="40" Type="float64" DefaultValue="1.0" MinVersion="R2007" />
    <Field Name="XRecordTag" Code="2" Type="string" DefaultValue='""' MinVersion="R2007" />
    <!-- entity has a trailing MText -->
    <Field Name="MText" Code="-1" Type="MText" DefaultValue="*NewMText()" />
    <!-- private tracking fields -->
    <Field Name="lastSubclassMarker" Code="-1" Type="string" DefaultValue='""' />
    <Field Name="isVersionSet" Code="-1" Type="bool" DefaultValue="false" />
    <Field Name="xrecCode70Count" Code="-1" Type="int" DefaultValue="0" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbText"' MinVersion="R13" />
      <WriteField Field="Thickness" />
      <WriteField Field="Location" />
      <WriteField Field="TextHeight" />
      <WriteField Field="Value" />
      <WriteSpecificValue Code="100" Value='"AcDbAttributeDefinition"' MinVersion="R13" />
      <WriteField Field="Rotation" />
      <WriteField Field="RelativeXScaleFactor" />
      <WriteField Field="ObliqueAngle" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="TextGenerationFlags" />
      <WriteField Field="HorizontalTextJustification" />
      <WriteField Field="SecondAlignmentPoint" />
      <WriteField Field="Normal" />
      <WriteSpecificValue Code="100" Value='"AcDbAttributeDefinition"' MinVersion="R13" />
      <WriteField Field="Version" />
      <WriteField Field="Prompt" />
      <WriteField Field="TextTag" />
      <WriteField Field="Flags" />
      <WriteField Field="FieldLength" />
      <WriteField Field="VerticalTextJustification" />
      <WriteField Field="IsLockedInBlock" />
      <WriteSpecificValue Code="100" Value='"AcDbXrecord"' MinVersion="R2007" />
      <WriteField Field="KeepDuplicateRecords" />
      <WriteField Field="MTextFlag" />
      <WriteField Field="IsReallyLocked" />
      <WriteSpecificValue Code="70" Value="int16(len(this.SecondaryAttributeHandles))" MinVersion="R2007" />
      <WriteField Field="SecondaryAttributeHandles" />
      <WriteField Field="AlignmentPoint" />
      <WriteField Field="AnnotationScale" />
      <WriteField Field="XRecordTag" />
    </WriteOrder>
  </Entity>
  <!--

  ATTRIB

    -->
  <Entity Name="Attribute" SubclassMarker="nil" TypeString="ATTRIB" GenerateReader="false">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="TextHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Value" Code="1" Type="string" DefaultValue='""' />
    <Field Name="Version" Code="280" Type="Version" DefaultValue="VersionR2010" ReadConverter="Version(%v)" WriteConverter="int16(%v)" MinVersion="R2010" />
    <Field Name="AttributeTag" Code="2" Type="string" DefaultValue='""' />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsInvisible" Mask="1" />
      <Flag Name="IsConstant" Mask="2" />
      <Flag Name="IsInputVerificationRequired" Mask="4" />
      <Flag Name="IsAttributePresent" Mask="8" />
    </Field>
    <Field Name="FieldLength" Code="73" Type="int16" DefaultValue="0" DisableWritingDefault="true" />
    <Field Name="Rotation" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RelativeXScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ObliqueAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="IsTextBackward" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Field>
    <Field Name="HorizontalTextJustification" Code="72" Type="HorizontalTextJustification" DefaultValue="HorizontalTextJustificationLeft" ReadConverter="HorizontalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="VerticalTextJustification" Code="74" Type="VerticalTextJustification" DefaultValue="VerticalTextJustificationBaseline" ReadConverter="VerticalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" MinVersion="R12" />
    <Field Name="SecondAlignmentPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="IsLockedInBlock" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="KeepDuplicateRecords" Code="280" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="MTextFlag" Code="70" Type="MTextFlag" DefaultValue="MTextFlagMultilineAttribute" ReadConverter="MTextFlag(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="IsReallyLocked" Code="70" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" MinVersion="R2007" />
    <Field Name="secondaryAttributeCount" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R2007" />
    <Field Name="secondaryAttributeHandles" Code="340" Type="string" DefaultValue="[]string{}" AllowMultiples="true" MinVersion="R2007" />
    <Field Name="AlignmentPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" MinVersion="R2007" />
    <Field Name="AnnotationScale" Code="40" Type="float64" DefaultValue="1.0" MinVersion="R2007" />
    <Field Name="XRecordTag" Code="2" Type="string" DefaultValue='""' MinVersion="R2007" />
    <!-- entity has a trailing MText -->
    <Field Name="MText" Code="-1" Type="MText" DefaultValue="*NewMText()" />
    <!-- private tracking fields -->
    <Field Name="lastSubclassMarker" Code="-1" Type="string" DefaultValue='""' />
    <Field Name="isVersionSet" Code="-1" Type="bool" DefaultValue="false" />
    <Field Name="xrecCode70Count" Code="-1" Type="int" DefaultValue="0" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbText"' MinVersion="R13" />
      <WriteField Field="Thickness" />
      <WriteField Field="Location" />
      <WriteField Field="TextHeight" />
      <WriteField Field="Value" />
      <WriteSpecificValue Code="100" Value='"AcDbAttribute"' MinVersion="R13" />
      <WriteField Field="Version" />
      <WriteField Field="AttributeTag" />
      <WriteField Field="Flags" />
      <WriteField Field="FieldLength" />
      <WriteField Field="Rotation" />
      <WriteField Field="RelativeXScaleFactor" />
      <WriteField Field="ObliqueAngle" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="TextGenerationFlags" />
      <WriteField Field="HorizontalTextJustification" />
      <WriteField Field="VerticalTextJustification" />
      <WriteField Field="SecondAlignmentPoint" />
      <WriteField Field="Normal" />
      <WriteField Field="IsLockedInBlock" />
      <WriteSpecificValue Code="100" Value='"AcDbXrecord"' MinVersion="R2007" />
      <WriteField Field="KeepDuplicateRecords" />
      <WriteField Field="MTextFlag" />
      <WriteField Field="IsReallyLocked" />
      <WriteSpecificValue Code="70" Value="int16(len(this.secondaryAttributeHandles))" MinVersion="R2007" />
      <WriteField Field="secondaryAttributeHandles" />
      <WriteField Field="AlignmentPoint" />
      <WriteField Field="AnnotationScale" />
      <WriteField Field="XRecordTag" />
    </WriteOrder>
  </Entity>
  <!--

  BODY

  -->
  <Entity Name="Body" SubclassMarker="AcDbModelerGeometry" TypeString="BODY" MinVersion="R13">
    <Field Name="FormatVersionNumber" Code="70" Type="int16" DefaultValue="1" />
    <Field Name="CustomData" Code="1" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="CustomData2" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
  </Entity>
  <!--

  CIRCLE

  -->
  <Entity Name="Circle" SubclassMarker="AcDbCircle" TypeString="CIRCLE">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Center" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Radius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  DIMENSION

  -->
  <Interface Name="Dimension">
    <Field Name="Version" Code="280" Type="Version" DefaultValue="VersionR2010" ReadConverter="Version(%v)" WriteConverter="int16(%v)" MinVersion="R2010" />
    <Field Name="BlockName" Code="2" Type="string" DefaultValue='"*MODEL_SPACE"' />
    <Field Name="DefinitionPoint1" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="TextMidPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="DimensionType" Code="70" Type="DimensionType" DefaultValue="DimensionTypeAligned" ReadConverter="DimensionType(%v)" WriteConverter="int16(%v)" />
    <Field Name="AttachmentPoint" Code="71" Type="AttachmentPoint" DefaultValue="AttachmentPointTopLeft" ReadConverter="AttachmentPoint(%v)" WriteConverter="int16(%v)" MinVersion="R2000" />
    <Field Name="TextLineSpacingStyle" Code="72" Type="TextLineSpacingStyle" DefaultValue="TextLineSpacingStyleAtLeast" ReadConverter="TextLineSpacingStyle(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" MinVersion="R2000" />
    <Field Name="TextLineSpacingFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" MinVersion="R2000" />
    <Field Name="ActualMeasurement" Code="42" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" ProtectedSet="true" MinVersion="R2000" />
    <Field Name="Text" Code="1" Type="string" DefaultValue='"&lt;&gt;"' />
    <Field Name="TextRotationAngle" Code="53" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="HorizontalDirectionAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="DimensionStyleName" Code="3" Type="string" DefaultValue='"STANDARD"' MinVersion="R12" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbDimension"' />
      <WriteField Field="Version" />
      <WriteField Field="BlockName" />
      <WriteField Field="DefinitionPoint1" />
      <WriteField Field="TextMidPoint" />
      <WriteField Field="DimensionType" />
      <WriteField Field="AttachmentPoint" />
      <WriteField Field="TextLineSpacingStyle" />
      <WriteField Field="TextLineSpacingFactor" />
      <WriteField Field="ActualMeasurement" />
      <WriteField Field="Text" />
      <WriteField Field="TextRotationAngle" />
      <WriteField Field="HorizontalDirectionAngle" />
      <WriteField Field="Normal" />
      <WriteField Field="DimensionStyleName" />
    </WriteOrder>
  </Interface>
  <Entity Name="dimensionHelper" TypeString="DIMENSION" ImplementInterfaces="Entity,Dimension" GenerateReader="false" GenerateWriter="false">
    <Field Name="collectedPairs" Type="CodePair" DefaultValue="[]CodePair{}" AllowMultiples="true" />
  </Entity>
  <Entity Name="AlignedDimension" SubclassMarker="AcDbAlignedDimension" TypeString="DIMENSION" Tag="Aligned" ImplementInterfaces="Entity,Dimension">
    <Field Name="DefinitionPoint2" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="DefinitionPoint3" Code="14" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="14,24,34" />
  </Entity>
  <Entity Name="RotatedDimension" SubclassMarker="AcDbAlignedDimension" TypeString="DIMENSION" Tag="RotatedHorizontalOrVertical" ImplementInterfaces="Entity,Dimension">
    <Field Name="InsertionPoint" Code="12" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="12,22,32" />
    <Field Name="DefinitionPoint2" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="DefinitionPoint3" Code="14" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="14,24,34" />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="ExtensionLineAngle" Code="52" Type="float64" DefaultValue="0.0" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbAlignedDimension"' MinVersion="R13" />
      <WriteField Field="InsertionPoint" />
      <WriteField Field="DefinitionPoint2" />
      <WriteField Field="DefinitionPoint3" />
      <WriteField Field="RotationAngle" />
      <WriteField Field="ExtensionLineAngle" />
      <WriteSpecificValue Code="100" Value='"AcDbRotatedDimension"' MinVersion="R13" />
    </WriteOrder>
  </Entity>
  <Entity Name="RadialDimension" SubclassMarker="AcDbRadialDimension" TypeString="DIMENSION" Tag="Radius" ImplementInterfaces="Entity,Dimension">
    <Field Name="DefinitionPoint2" Code="15" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="15,25,35" />
    <Field Name="LeaderLength" Code="40" Type="float64" DefaultValue="0.0" />
  </Entity>
  <Entity Name="DiameterDimension" SubclassMarker="AcDbDiametricDimension" TypeString="DIMENSION" Tag="Diameter" ImplementInterfaces="Entity,Dimension">
    <Field Name="DefinitionPoint2" Code="15" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="15,25,35" />
    <Field Name="LeaderLength" Code="40" Type="float64" DefaultValue="0.0" />
  </Entity>
  <Entity Name="AngularThreePointDimension" SubclassMarker="AcDb3PointAngularDimension" TypeString="DIMENSION" Tag="AngularThreePoint" ImplementInterfaces="Entity,Dimension">
    <Field Name="DefinitionPoint2" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="DefinitionPoint3" Code="14" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="14,24,34" />
    <Field Name="DefinitionPoint4" Code="15" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="15,25,35" />
    <Field Name="DefinitionPoint5" Code="16" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="16,26,36" />
  </Entity>
  <Entity Name="OrdinateDimension" SubclassMarker="AcDbOrdinateDimension" TypeString="DIMENSION" Tag="Ordinate" ImplementInterfaces="Entity,Dimension" MinVersion="R11">
    <Field Name="DefinitionPoint2" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="DefinitionPoint3" Code="14" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="14,24,34" />
  </Entity>
  <!--

  ELLIPSE

  -->
  <Entity Name="Ellipse" SubclassMarker="AcDbEllipse" TypeString="ELLIPSE">
    <Field Name="Center" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="MajorAxis" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="MinorAxisRatio" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="StartAngle" Code="41" Type="float64" DefaultValue="0.0" Comment="Ellipse start angle in radians." />
    <Field Name="EndAngle" Code="42" Type="float64" DefaultValue="math.Pi * 2.0" Comment="Ellipse end angle in radians." />
  </Entity>
  <!--

  HATCH

  -->
  <!-- TODO MinVersion="R14" -->
  <!--

  HELIX

  -->
  <Entity Name="Helix" SubclassMarker="AcDbHelix" TypeString="HELIX" MinVersion="R2007">
    <Field Name="MajorReleaseNumber" Code="90" Type="int" DefaultValue="0" />
    <Field Name="MaintainenceReleaseNumber" Code="91" Type="int" DefaultValue="0" />
    <Field Name="AxisBasePoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="StartPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="AxisVector" Code="12" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="12,22,32" />
    <Field Name="Radius" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="NumberOfTurns" Code="41" Type="float64" DefaultValue="0.0" />
    <Field Name="TurnHeight" Code="42" Type="float64" DefaultValue="0.0" />
    <Field Name="IsRightHanded" Code="290" Type="bool" DefaultValue="false" />
    <Field Name="Constraint" Code="280" Type="HelixConstraint" DefaultValue="HelixConstraintConstrainTurnHeight" ReadConverter="HelixConstraint(%v)" WriteConverter="int16(%v)" />
  </Entity>
  <!--

  IMAGE

    -->
  <Interface Name="RasterImage">
    <Field Name="subclassMarker" Code="100" Type="string" DefaultValue='""' />
    <Field Name="ClassVersion" Code="90" Type="int" DefaultValue="0" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" Comment="The location of the bottom-left corner of the image" />
    <Field Name="UVector" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
    <Field Name="VVector" Code="12" Type="Vector" DefaultValue="*NewYAxis()" CodeOverrides="12,22,32" />
    <Field Name="ImageSize" Code="13" Type="Vector" DefaultValue="*NewZeroVector()" CodeOverrides="13,23" Comment="Image size in pixels" />
    <Field Name="imageDefinitionHandle" Code="340" Type="string" DefaultValue='""' DisableWritingDefault="true" />
    <Field Name="DisplayOptionsFlags" Code="70" Type="int" DefaultValue="1" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="ShowImage" Mask="1" />
      <Flag Name="ShowImageWhenNotAligned" Mask="2" />
      <Flag Name="UseClippingBoundary" Mask="4" />
      <Flag Name="UseTransparency" Mask="8" />
    </Field>
    <Field Name="UseClipping" Code="280" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="Brightness" Code="281" Type="int16" DefaultValue="50" />
    <Field Name="Contrast" Code="282" Type="int16" DefaultValue="50" />
    <Field Name="Fade" Code="283" Type="int16" DefaultValue="0" />
    <Field Name="imageDefinitionReactorHandle" Code="360" Type="string" DefaultValue='""' DisableWritingDefault="true" />
    <Field Name="ClippingType" Code="71" Type="ImageClippingBoundaryType" DefaultValue="ImageClippingBoundaryTypeRectangular" ReadConverter="ImageClippingBoundaryType(%v)" WriteConverter="int16(%v)" />
    <Field Name="ClippingVertices" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="clippingVertexCount" Code="91" Type="int" DefaultValue="0" />
    <Field Name="clippingVerticesX" Code="14" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="clippingVerticesY" Code="24" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="IsInsideClipping" Code="290" Type="bool" DefaultValue="false" MinVersion="R2010" />
    <WriteOrder>
      <WriteField Field="subclassMarker" />
      <WriteField Field="ClassVersion" />
      <WriteField Field="Location" />
      <WriteField Field="UVector" />
      <WriteField Field="VVector" />
      <WriteField Field="ImageSize" />
      <WriteField Field="imageDefinitionHandle" />
      <WriteField Field="DisplayOptionsFlags" />
      <WriteField Field="UseClipping" />
      <WriteField Field="Brightness" />
      <WriteField Field="Contrast" />
      <WriteField Field="Fade" />
      <WriteField Field="imageDefinitionReactorHandle" />
      <WriteField Field="ClippingType" />
      <WriteSpecificValue Code="91" Value="len(this.ClippingVertices())" />
      <Foreach Field="ClippingVertices()">
        <WriteSpecificValue Code="14" Value="item.X" />
        <WriteSpecificValue Code="24" Value="item.Y" />
      </Foreach>
      <WriteField Field="IsInsideClipping" />
    </WriteOrder>
  </Interface>
  <Entity Name="Image" TypeString="IMAGE" ImplementInterfaces="Entity,RasterImage" MinVersion="R14" />
  <!--

  INSERT

  -->
  <Entity Name="Insert" SubclassMarker="AcDbBlockReference" TypeString="INSERT">
    <Field Name="HasAttributes" Code="66" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" DisableWritingDefault="true" />
    <Field Name="Name" Code="2" Type="string" DefaultValue='""' />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="XScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="YScaleFactor" Code="42" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ZScaleFactor" Code="43" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="Rotation" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ColumnCount" Code="70" Type="int16" DefaultValue="1" DisableWritingDefault="true" />
    <Field Name="RowCount" Code="71" Type="int16" DefaultValue="1" DisableWritingDefault="true" />
    <Field Name="ColumnSpacing" Code="44" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RowSpacing" Code="45" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="210,220,230" />
    <!-- entity has trailing attributes and seqend -->
    <Field Name="Attributes" Code="-1" Type="Attribute" DefaultValue="[]Attribute{}" AllowMultiples="true" />
    <Field Name="seqend" Code="-1" Type="Seqend" DefaultValue="*NewSeqend()" />
  </Entity>
  <!--

  LEADER

  -->
  <Entity Name="Leader" SubclassMarker="AcDbLeader" TypeString="LEADER" MinVersion="R13">
    <Field Name="DimensionStyleName" Code="3" Type="string" DefaultValue='""' />
    <Field Name="UseArrowheads" Code="71" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="PathType" Code="72" Type="LeaderPathType" DefaultValue="LeaderPathTypeStraightLineSegments" ReadConverter="LeaderPathType(%v)" WriteConverter="int16(%v)" />
    <Field Name="AnnotationType" Code="73" Type="LeaderCreationAnnotationType" DefaultValue="LeaderCreationAnnotationTypeNoAnnotation" ReadConverter="LeaderCreationAnnotationType(%v)" WriteConverter="int16(%v)" />
    <Field Name="HooklineDirection" Code="74" Type="LeaderHooklineDirection" DefaultValue="LeaderHooklineDirectionOppositeFromHorizontalVector" ReadConverter="LeaderHooklineDirection(%v)" WriteConverter="int16(%v)" />
    <Field Name="UseHookline" Code="75" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="TextAnnotationHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="TextAnnotationWidth" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="Vertices" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="vertexCount" Code="76" Type="int" DefaultValue="0" ReadConverter="int(%v)" />
    <Field Name="verticesX" Code="10" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="verticesY" Code="20" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="verticesZ" Code="30" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="OverrideColor" Code="77" Type="Color" DefaultValue="ByBlock()" DisableWritingDefault="true" ReadConverter="Color(%v)" WriteConverter="int16(%v)" />
    <Field Name="AssociatedAnnotationReference" Code="340" Type="string" DefaultValue='""' />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="210,220,230" />
    <Field Name="Right" Code="211" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="211,221,231" />
    <Field Name="BlockOffset" Code="212" Type="Vector" DefaultValue="*NewZeroVector()" CodeOverrides="212,222,232" />
    <Field Name="AnnotationOffset" Code="213" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="213,223,233" MinVersion="R14" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbLeader"' />
      <WriteField Field="DimensionStyleName" />
      <WriteField Field="UseArrowheads" />
      <WriteField Field="PathType" />
      <WriteField Field="AnnotationType" />
      <WriteField Field="HooklineDirection" />
      <WriteField Field="UseHookline" />
      <WriteField Field="TextAnnotationHeight" />
      <WriteField Field="TextAnnotationWidth" />
      <WriteSpecificValue Code="76" Value="int16(len(this.Vertices))" />
      <Foreach Field="Vertices">
        <WriteSpecificValue Code="10" Value="item.X" />
        <WriteSpecificValue Code="20" Value="item.Y" />
        <WriteSpecificValue Code="30" Value="item.Z" />
      </Foreach>
      <WriteField Field="OverrideColor" />
      <WriteField Field="AssociatedAnnotationReference" />
      <WriteField Field="Normal" />
      <WriteField Field="Right" />
      <WriteField Field="BlockOffset" />
      <WriteField Field="AnnotationOffset" />
    </WriteOrder>
  </Entity>
  <!--

  LIGHT

  -->
  <Entity Name="Light" SubclassMarker="AcDbLight" TypeString="LIGHT" MinVersion="R2007">
    <Field Name="VersionNumber" Code="90" Type="int" DefaultValue="0" />
    <Field Name="Name" Code="1" Type="string" DefaultValue='""' />
    <Field Name="LightType" Code="70" Type="LightType" DefaultValue="LightTypeDistant" ReadConverter="LightType(%v)" WriteConverter="int16(%v)" />
    <Field Name="IsActive" Code="290" Type="bool" DefaultValue="true" />
    <Field Name="PlotGlyph" Code="291" Type="bool" DefaultValue="true" />
    <Field Name="Intensity" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Position" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="TargetLocation" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="AttentuationType" Code="72" Type="LightAttenuationType" DefaultValue="LightAttenuationTypeNone" ReadConverter="LightAttenuationType(%v)" WriteConverter="int16(%v)" />
    <Field Name="UseAttenuationLimits" Code="292" Type="bool" DefaultValue="true" />
    <Field Name="AttenuationStartLimit" Code="41" Type="float64" DefaultValue="0.0" />
    <Field Name="AttenuationEndLimit" Code="42" Type="float64" DefaultValue="1.0" />
    <Field Name="HotspotAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="FalloffAngle" Code="51" Type="float64" DefaultValue="0.0" />
    <Field Name="CastShadows" Code="293" Type="bool" DefaultValue="true" />
    <Field Name="ShadowType" Code="73" Type="ShadowType" DefaultValue="ShadowTypeRayTraced" ReadConverter="ShadowType(%v)" WriteConverter="int16(%v)" />
    <Field Name="ShadowMapSize" Code="91" Type="int" DefaultValue="0" />
    <Field Name="ShadowMapSoftness" Code="280" Type="int16" DefaultValue="0" />
  </Entity>
  <!--

  LINE

  -->
  <Entity Name="Line" SubclassMarker="AcDbLine" TypeString="LINE,3DLINE">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="P1" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="P2" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  LWPOLYLINE

  -->
  <Entity Name="LWPolyline" SubclassMarker="AcDbPolyline" TypeString="LWPOLYLINE" MinVersion="R14" GenerateReader="false">
    <Field Name="flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="IsPLineGen" Mask="128" />
    </Field>
    <Field Name="ConstantWidth" Code="43" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="vertexCount" Code="90" Type="int" DefaultValue="0" />
    <Field Name="Vertices" Code="-1" Type="LwVertex" DefaultValue="[]LwVertex{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbPolyline"' />
      <WriteSpecificValue Code="90" Value="len(this.Vertices)" />
      <WriteField Field="flags" />
      <WriteField Field="ConstantWidth" />
      <WriteSpecificValue Code="38" Value="this.Elevation()" WriteCondition="this.Elevation() != 0.0" />
      <WriteField Field="Thickness" />
      <Foreach Field="Vertices">
        <WriteSpecificValue Code="10" Value="item.X" />
        <WriteSpecificValue Code="20" Value="item.Y" />
        <WriteSpecificValue Code="91" Value="item.ID" WriteCondition="item.ID != 0" MinVersion="R2013" />
        <WriteSpecificValue Code="40" Value="item.StartingWidth" WriteCondition="item.StartingWidth != 0.0" />
        <WriteSpecificValue Code="41" Value="item.EndingWidth" WriteCondition="item.EndingWidth != 0.0" />
        <WriteSpecificValue Code="42" Value="item.Bulge" WriteCondition="item.Bulge != 0.0" />
      </Foreach>
      <WriteField Field="ExtrusionDirection" />
    </WriteOrder>
  </Entity>
  <!--

  MESH

  -->
  <!-- TODO MinVersion=R2011 -->
  <!--

  MLEADER

  -->
  <!-- TODO MinVersion=R2007 -->
  <!--

  MLINE

  -->
  <Entity Name="MLine" SubclassMarker="AcDbMline" TypeString="MLINE" MinVersion="R13">
    <Field Name="StyleName" Code="2" Type="string" DefaultValue='""' />
    <Field Name="styleHandle" Code="340" Type="string" DefaultValue='""' DisableWritingDefault="true" />
    <Field Name="ScaleFactor" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Justification" Code="70" Type="Justification" DefaultValue="JustificationTop" ReadConverter="Justification(%v)" WriteConverter="int16(%v)" />
    <Field Name="Flags" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="HasAtLeastOneVertex" Mask="1" />
      <Flag Name="IsClosed" Mask="2" />
      <Flag Name="SuppressStartCaps" Mask="4" />
      <Flag Name="SuppressEndCaps" Mask="8" />
    </Field>
    <Field Name="vertexCount" Code="72" Type="int" DefaultValue="0" ReadConverter="int(%v)" />
    <Field Name="StyleElementCount" Code="73" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="StartPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="210,220,230" DisableWritingDefault="true" />
    <Field Name="Vertices" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="vertexX" Code="11" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="vertexY" Code="21" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="vertexZ" Code="31" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="SegmentDirections" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="segmentDirectionX" Code="12" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="segmentDirectionY" Code="22" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="segmentDirectionZ" Code="32" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="MiterDirections" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="miterDirectionX" Code="13" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="miterDirectionY" Code="23" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="miterDirectionZ" Code="33" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="parameterCount" Code="74" Type="int" DefaultValue="0" ReadConverter="int(%v)" />
    <Field Name="Parameters" Code="41" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="areaFillParameterCount" Code="75" Type="int" DefaultValue="0" ReadConverter="int(%v)" />
    <Field Name="AreaFillParameters" Code="42" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbMline"' />
      <WriteField Field="StyleName" />
      <WriteField Field="styleHandle" />
      <WriteField Field="ScaleFactor" />
      <WriteField Field="Justification" />
      <WriteField Field="Flags" />
      <WriteSpecificValue Code="72" Value="int16(len(this.Vertices))" />
      <WriteField Field="StyleElementCount" />
      <WriteField Field="StartPoint" />
      <WriteField Field="Normal" />
      <Foreach Field="Vertices">
        <WriteSpecificValue Code="10" Value="item.X" />
        <WriteSpecificValue Code="20" Value="item.Y" />
        <WriteSpecificValue Code="30" Value="item.Z" />
      </Foreach>
      <Foreach Field="SegmentDirections">
        <WriteSpecificValue Code="11" Value="item.X" />
        <WriteSpecificValue Code="21" Value="item.Y" />
        <WriteSpecificValue Code="31" Value="item.Z" />
      </Foreach>
      <Foreach Field="MiterDirections">
        <WriteSpecificValue Code="12" Value="item.X" />
        <WriteSpecificValue Code="22" Value="item.Y" />
        <WriteSpecificValue Code="32" Value="item.Z" />
      </Foreach>
      <WriteSpecificValue Code="74" Value="int16(len(this.Parameters))" />
      <WriteField Field="Parameters" />
      <WriteSpecificValue Code="75" Value="int16(len(this.AreaFillParameters))" />
      <WriteField Field="AreaFillParameters" />
    </WriteOrder>
  </Entity>
  <!--

  MTEXT

  -->
  <Entity Name="MText" SubclassMarker="AcDbMText" TypeString="MTEXT" MinVersion="R13" GenerateReader="false">
    <Field Name="InsertionPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="InitialTextHeight" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="ReferenceRectangleWidth" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="AttachmentPoint" Code="71" Type="AttachmentPoint" DefaultValue="AttachmentPointTopLeft" ReadConverter="AttachmentPoint(%v)" WriteConverter="int16(%v)" />
    <Field Name="DrawingDirection" Code="72" Type="DrawingDirection" DefaultValue="DrawingDirectionLeftToRight" ReadConverter="DrawingDirection(%v)" WriteConverter="int16(%v)" />
    <Field Name="ExtendedText" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="Text" Code="1" Type="string" DefaultValue='""' />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="XAxisDirection" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
    <Field Name="HorizontalWidth" Code="42" Type="float64" DefaultValue="1.0" />
    <Field Name="VerticalHeight" Code="43" Type="float64" DefaultValue="1.0" />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="LineSpacingStyle" Code="73" Type="MTextLineSpacingStyle" DefaultValue="MTextLineSpacingStyleAtLeast" ReadConverter="MTextLineSpacingStyle(%v)" WriteConverter="int16(%v)" />
    <Field Name="LineSpacingFactor" Code="44" Type="float64" DefaultValue="1.0" />
    <Field Name="BackgroundFillSetting" Code="90" Type="BackgroundFillSetting" DefaultValue="BackgroundFillSettingOff" ReadConverter="BackgroundFillSetting(%v)" WriteConverter="int(%v)" />
    <Field Name="BackgroundColorRGB" Code="420" Type="int" DefaultValue="0" />
    <Field Name="BackgroundColorName" Code="430" Type="string" DefaultValue='""' />
    <Field Name="FillBoxScale" Code="45" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="BackgroundFillColor" Code="63" Type="Color" DefaultValue="ByLayer()" ReadConverter="Color(%v)" WriteConverter="int16(%v)" />
    <Field Name="BackgroundFillColorTransparency" Code="441" Type="int" DefaultValue="0" />
    <Field Name="ColumnType" Code="75" Type="int16" DefaultValue="0" />
    <Field Name="columnCount" Code="76" Type="int16" DefaultValue="0" WriteConverter="int16(%v)" />
    <Field Name="IsColumnFlowReversed" Code="78" Type="bool" DefaultValue="false" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="IsColumnAutoHeight" Code="79" Type="bool" DefaultValue="true" ReadConverter="boolFromShort(%v)" WriteConverter="shortFromBool(%v)" />
    <Field Name="ColumnWidth" Code="48" Type="float64" DefaultValue="0.0" />
    <Field Name="ColumnGutter" Code="49" Type="float64" DefaultValue="0.0" />
    <Field Name="ColumnHeights" Code="50" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <!-- private tracking fields -->
    <Field Name="readingColumnData" Code="-1" Type="bool" DefaultValue="false" />
    <Field Name="readColumnCount" Code="-1" Type="bool" DefaultValue="false" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbMText"' />
      <WriteField Field="InsertionPoint" />
      <WriteField Field="InitialTextHeight" />
      <WriteField Field="ReferenceRectangleWidth" />
      <WriteField Field="AttachmentPoint" />
      <WriteField Field="DrawingDirection" />
      <WriteField Field="ExtendedText" />
      <WriteField Field="Text" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="ExtrusionDirection" />
      <WriteField Field="XAxisDirection" />
      <WriteField Field="HorizontalWidth" />
      <WriteField Field="VerticalHeight" />
      <WriteField Field="RotationAngle" />
      <WriteField Field="LineSpacingStyle" />
      <WriteField Field="LineSpacingFactor" />
      <WriteField Field="BackgroundFillSetting" />
      <WriteField Field="BackgroundColorRGB" />
      <WriteField Field="BackgroundColorName" />
      <WriteField Field="FillBoxScale" />
      <WriteField Field="BackgroundFillColor" />
      <WriteField Field="BackgroundFillColorTransparency" />
      <WriteField Field="ColumnType" />
      <WriteField Field="columnCount" />
      <WriteField Field="IsColumnFlowReversed" />
      <WriteField Field="IsColumnAutoHeight" />
      <WriteField Field="ColumnWidth" />
      <WriteField Field="ColumnGutter" />
      <WriteSpecificValue Code="50" Value="float64(len(this.ColumnHeights))" />
      <WriteField Field="ColumnHeights" />
    </WriteOrder>
  </Entity>
  <!--

  OLEFRAME

  -->
  <Entity Name="OleFrame" SubclassMarker="AcDbOleFrame" TypeString="OLEFRAME" MinVersion="R13">
    <Field Name="VersionNumber" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="binaryDataLength" Code="90" Type="int" DefaultValue="0" />
    <Field Name="binaryDataStrings" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="BinaryData" Code="-1" Type="byte" DefaultValue="[]byte{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbOleFrame"' />
      <WriteField Field="VersionNumber" />
      <WriteField Field="binaryDataLength" />
      <Foreach Field="binaryDataStrings">
        <WriteSpecificValue Code="310" Value="item" />
      </Foreach>
      <WriteSpecificValue Code="1" Value='"OLE"' />
    </WriteOrder>
  </Entity>
  <!--

  OLE2FRAME

  -->
    <Entity Name="Ole2Frame" SubclassMarker="AcDbOle2Frame" TypeString="OLE2FRAME" MinVersion="R14">
    <Field Name="VersionNumber" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="Description" Code="3" Type="string" DefaultValue='""' />
    <Field Name="UpperLeftCorner" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="LowerRightCorner" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ObjectType" Code="71" Type="OleObjectType" DefaultValue="OleObjectTypeStatic" ReadConverter="OleObjectType(%v)" WriteConverter="int16(%v)" />
    <Field Name="TileMode" Code="72" Type="TileModeDescriptor" DefaultValue="TileModeDescriptorInTiledViewport" ReadConverter="TileModeDescriptor(%v)" WriteConverter="int16(%v)" />
    <Field Name="binaryDataLength" Code="90" Type="int" DefaultValue="0" />
    <Field Name="binaryDataStrings" Code="310" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="BinaryData" Code="-1" Type="byte" DefaultValue="[]byte{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbOle2Frame"' />
      <WriteField Field="VersionNumber" />
      <WriteField Field="Description" />
      <WriteField Field="UpperLeftCorner" />
      <WriteField Field="LowerRightCorner" />
      <WriteField Field="ObjectType" />
      <WriteField Field="TileMode" />
      <WriteField Field="binaryDataLength" />
      <Foreach Field="binaryDataStrings">
        <WriteSpecificValue Code="310" Value="item" />
      </Foreach>
      <WriteSpecificValue Code="1" Value='"OLE"' />
    </WriteOrder>
  </Entity>
  <!--

  POINT

  -->
  <Entity Name="ModelPoint" SubclassMarker="AcDbPoint" TypeString="POINT">
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="Angle" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
  </Entity>
  <!--

  POLYLINE

  -->
  <Entity Name="Polyline" SubclassMarker="nil" TypeString="POLYLINE" GenerateReader="false" GenerateWriter="false">
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="CurveFitVerticiesAdded" Mask="2" />
      <Flag Name="SplineFitVerticiesAdded" Mask="4" />
      <Flag Name="Is3DPolyline" Mask="8" />
      <Flag Name="Is3DPolygonMesh" Mask="16" />
      <Flag Name="IsPolygonMeshClosedInNDirection" Mask="32" />
      <Flag Name="IsPolyfaceMesh" Mask="64" />
      <Flag Name="IsLineTypePatternGeneratedContinuously" Mask="128" />
    </Field>
    <Field Name="DefaultStartingWidth" Code="40" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="DefaultEndingWidth" Code="41" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="PolygonMeshMVertexCount" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="PolygonMeshNVertexCount" Code="72" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SmoothSurfaceMDensity" Code="73" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SmoothSurfaceNDensity" Code="74" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SurfaceType" Code="75" Type="PolylineCurvedAndSmoothSurfaceType" DefaultValue="PolylineCurvedAndSmoothSurfaceTypeNone" ReadConverter="PolylineCurvedAndSmoothSurfaceType(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="CLO_PolylineType" Code="250" Type="PolylineType" DefaultValue="PolylineTypeBaseline" ReadConverter="PolylineTypeBaseline(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <!-- entity has trailing vertices and seqend -->
    <Field Name="Vertices" Code="-1" Type="Vertex" DefaultValue="[]Vertex{}" AllowMultiples="true" />
    <Field Name="seqend" Code="-1" Type="Seqend" DefaultValue="*NewSeqend()" />
  </Entity>
  <!--

  RAY

  -->
  <Entity Name="Ray" SubclassMarker="AcDbRay" TypeString="RAY" MinVersion="R13">
    <Field Name="StartPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="UnitDirectionVector" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
  </Entity>
  <!--

  REGION

  -->
  <Entity Name="Region" SubclassMarker="AcDbModelerGeometry" TypeString="REGION" MinVersion="R13">
    <Field Name="FormatVersionNumber" Code="70" Type="int16" DefaultValue="1" />
    <Field Name="CustomData" Code="1" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
    <Field Name="CustomData2" Code="3" Type="string" DefaultValue="[]string{}" AllowMultiples="true" />
  </Entity>
  <!--

  RTEXT

  -->
  <Entity Name="RText" SubclassMarker="RText" TypeString="RTEXT" MinVersion="R2000" MaxVersion="R2000">
    <Field Name="InsertionPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="TextHeight" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="TextStyle" Code="7" Type="string" DefaultValue='"STANDARD"' />
    <Field Name="TypeFlags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsExpression" Mask="1" />
      <Flag Name="IsInlineMTextSequencesEnabled" Mask="2" />
    </Field>
    <Field Name="Contents" Code="1" Type="string" DefaultValue='""' />
  </Entity>
  <!--

  SECTION

  -->
  <Entity Name="Section" SubclassMarker="AcDbSection" TypeString="SECTION" GenerateReader="false" MinVersion="R2007">
    <Field Name="State" Code="90" Type="int" DefaultValue="0" />
    <Field Name="Flags" Code="91" Type="int" DefaultValue="0" />
    <Field Name="Name" Code="1" Type="string" DefaultValue='""' />
    <Field Name="VerticalDirection" Code="10" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="10,20,30" />
    <Field Name="TopHeight" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="BottomHeight" Code="41" Type="float64" DefaultValue="0.0" />
    <Field Name="IndicatorTransparency" Code="70" Type="int16" DefaultValue="0" />
    <Field Name="IndicatorColor" Code="63" Type="Color" DefaultValue="ByLayer()" ReadConverter="Color(%v)" WriteConverter="int16(%v)" />
    <Field Name="IndicatorColorName" Code="411" Type="string" DefaultValue='""' />
    <Field Name="vertexCount" Code="92" Type="int" DefaultValue="0" />
    <Field Name="Vertices" Code="11" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" CodeOverrides="11,21,31" />
    <Field Name="backLineVertexCount" Code="93" Type="int" DefaultValue="0" />
    <Field Name="BackLineVertices" Code="12" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" CodeOverrides="12,22,32" />
    <Field Name="GeometrySettingsHandle" Code="360" Type="string" DefaultValue='""' DisableWritingDefault="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbSection"' />
      <WriteField Field="State" />
      <WriteField Field="Flags" />
      <WriteField Field="Name" />
      <WriteField Field="VerticalDirection" />
      <WriteField Field="TopHeight" />
      <WriteField Field="BottomHeight" />
      <WriteField Field="IndicatorTransparency" />
      <WriteField Field="IndicatorColor" />
      <WriteField Field="IndicatorColorName" />
      <WriteSpecificValue Code="92" Value="len(this.Vertices)" />
      <Foreach Field="Vertices">
        <WriteSpecificValue Code="11" Value="item.X" />
        <WriteSpecificValue Code="21" Value="item.Y" />
        <WriteSpecificValue Code="31" Value="item.Z" />
      </Foreach>
      <WriteSpecificValue Code="93" Value="len(this.BackLineVertices)" />
      <Foreach Field="BackLineVertices">
        <WriteSpecificValue Code="12" Value="item.X" />
        <WriteSpecificValue Code="22" Value="item.Y" />
        <WriteSpecificValue Code="32" Value="item.Z" />
      </Foreach>
      <WriteField Field="GeometrySettingsHandle" />
    </WriteOrder>
  </Entity>
  <!--

  SEQEND

  -->
  <Entity Name="Seqend" SubclassMarker="nil" TypeString="SEQEND" GenerateReader="false">
    <!-- empty entity -->
    <WriteOrder>
      <NOP />
    </WriteOrder>
  </Entity>
  <!--

  SHAPE

  -->
  <Entity Name="Shape" SubclassMarker="AcDbShape" TypeString="SHAPE">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Size" Code="40" Type="float64" DefaultValue="0.0" />
    <Field Name="Name" Code="2" Type="string" DefaultValue='""' />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RelativeXScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ObliqueAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  SOLID

  -->
  <Entity Name="Solid" SubclassMarker="AcDbTrace" TypeString="SOLID">
    <Field Name="FirstCorner" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="SecondCorner" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ThirdCorner" Code="12" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="12,22,32" />
    <Field Name="FourthCorner" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  SPLINE

  -->
  <Entity Name="Spline" SubclassMarker="AcDbSpline" TypeString="SPLINE" GenerateReader="false" MinVersion="R13">
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="210,220,230" />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsClosed" Mask="1" />
      <Flag Name="IsPeriodic" Mask="2" />
      <Flag Name="IsRational" Mask="4" />
      <Flag Name="IsPlanar" Mask="8" />
      <Flag Name="IsLinear" Mask="16" />
    </Field>
    <Field Name="DegreeOfCurve" Code="71" Type="int" DefaultValue="1" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="numberOfKnots" Code="72" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="numberOfControlPoints" Code="73" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="numberOfFitPoints" Code="74" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" />
    <Field Name="KnotTolerance" Code="42" Type="float64" DefaultValue="0.0000001" DisableWritingDefault="true" />
    <Field Name="ControlPointTolerance" Code="43" Type="float64" DefaultValue="0.0000001" DisableWritingDefault="true" />
    <Field Name="FitTolerance" Code="44" Type="float64" DefaultValue="0.0000001" DisableWritingDefault="true" />
    <Field Name="StartTangent" Code="12" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="12,22,32" />
    <Field Name="EndTangent" Code="13" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="13,23,33" />
    <Field Name="KnotValues" Code="40" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="weights" Code="41" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="ControlPoints" Code="10" Type="ControlPoint" DefaultValue="[]ControlPoint{}" AllowMultiples="true" />
    <Field Name="FitPoints" Code="11" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbSpline"' />
      <WriteField Field="Normal" />
      <WriteField Field="Flags" />
      <WriteField Field="DegreeOfCurve" />
      <WriteSpecificValue Code="72" Value="int16(len(this.KnotValues))" />
      <WriteSpecificValue Code="73" Value="int16(len(this.ControlPoints))" />
      <WriteSpecificValue Code="74" Value="int16(len(this.FitPoints))" />
      <WriteField Field="KnotTolerance" />
      <WriteField Field="ControlPointTolerance" />
      <WriteField Field="FitTolerance" />
      <WriteField Field="StartTangent" />
      <WriteField Field="EndTangent" />
      <WriteField Field="KnotValues" />
      <Foreach Field="ControlPoints" WriteCondition="this.shouldWriteWeights()">
        <WriteSpecificValue Code="41" Value="item.Weight" />
      </Foreach>
      <Foreach Field="ControlPoints">
        <WriteSpecificValue Code="10" Value="item.Point.X" />
        <WriteSpecificValue Code="20" Value="item.Point.Y" />
        <WriteSpecificValue Code="30" Value="item.Point.Z" />
      </Foreach>
      <Foreach Field="FitPoints">
        <WriteSpecificValue Code="11" Value="item.X" />
        <WriteSpecificValue Code="21" Value="item.Y" />
        <WriteSpecificValue Code="31" Value="item.Z" />
      </Foreach>
    </WriteOrder>
  </Entity>
  <!--

  SURFACE

  -->
  <!-- TODO MinVersion=R2007 -->
  <!--

  TABLE

  -->
  <!-- TODO MinVersion=R2005 -->
  <!--

  TEXT

  -->
  <Entity Name="Text" SubclassMarker="AcDbText" TypeString="TEXT">
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="Height" Code="40" Type="float64" DefaultValue="1.0" />
    <Field Name="Value" Code="1" Type="string" DefaultValue='""' />
    <Field Name="Rotation" Code="50" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="RelativeXScaleFactor" Code="41" Type="float64" DefaultValue="1.0" DisableWritingDefault="true" />
    <Field Name="ObliqueAngle" Code="51" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="TextStyleName" Code="7" Type="string" DefaultValue='"STANDARD"' DisableWritingDefault="true" />
    <Field Name="TextGenerationFlags" Code="71" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true">
      <Flag Name="IsTextBackwards" Mask="2" />
      <Flag Name="IsTextUpsideDown" Mask="4" />
    </Field>
    <Field Name="HorizontalTextJustification" Code="72" Type="HorizontalTextJustification" DefaultValue="HorizontalTextJustificationLeft" ReadConverter="HorizontalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <Field Name="SecondAlignmentPoint" Code="11" Type="Point" DefaultValue="*NewOrigin()" DisableWritingDefault="true" CodeOverrides="11,21,31" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="VerticalTextJustification" Code="73" Type="VerticalTextJustification" DefaultValue="VerticalTextJustificationBaseline" ReadConverter="VerticalTextJustification(%v)" WriteConverter="int16(%v)" DisableWritingDefault="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbText"' />
      <WriteField Field="Thickness" />
      <WriteField Field="Location" />
      <WriteField Field="Height" />
      <WriteField Field="Value" />
      <WriteField Field="Rotation" />
      <WriteField Field="RelativeXScaleFactor" />
      <WriteField Field="ObliqueAngle" />
      <WriteField Field="TextStyleName" />
      <WriteField Field="TextGenerationFlags" />
      <WriteField Field="HorizontalTextJustification" />
      <WriteField Field="SecondAlignmentPoint" />
      <WriteField Field="Normal" />
      <WriteField Field="VerticalTextJustification" />
      <WriteSpecificValue Code="100" Value='"AcDbText"' />
    </WriteOrder>
  </Entity>
  <!--

  TOLERANCE

  -->
  <Entity Name="Tolerance" SubclassMarker="AcDbFcf" TypeString="TOLERANCE" MinVersion="R13">
    <Field Name="DimensionStyleName" Code="3" Type="string" DefaultValue='""' />
    <Field Name="InsertionPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="DisplayText" Code="1" Type="string" DefaultValue='""' MinVersion="R2000" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
    <Field Name="DirectionVector" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
  </Entity>
  <!--

  TRACE

  -->
  <Entity Name="Trace" SubclassMarker="AcDbTrace" TypeString="TRACE">
    <Field Name="FirstCorner" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="SecondCorner" Code="11" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="11,21,31" />
    <Field Name="ThirdCorner" Code="12" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="12,22,32" />
    <Field Name="FourthCorner" Code="13" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="13,23,33" />
    <Field Name="Thickness" Code="39" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="ExtrusionDirection" Code="210" Type="Vector" DefaultValue="*NewZAxis()" DisableWritingDefault="true" CodeOverrides="210,220,230" />
  </Entity>
  <!--

  UNDERLAY

  -->
  <Interface Name="Underlay">
    <Field Name="ObjectHandle" Code="340" Type="string" DefaultValue='""' />
    <Field Name="InsertionPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="XScale" Code="41" Type="float64" DefaultValue="1.0" />
    <Field Name="YScale" Code="42" Type="float64" DefaultValue="1.0" />
    <Field Name="ZScale" Code="43" Type="float64" DefaultValue="1.0" />
    <Field Name="RotationAngle" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="Normal" Code="210" Type="Vector" DefaultValue="*NewZAxis()" CodeOverrides="210,220,230" />
    <Field Name="Flags" Code="280" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsClippingOn" Mask="1" />
      <Flag Name="IsUnderlayOn" Mask="2" />
      <Flag Name="IsMonochrome" Mask="4" />
      <Flag Name="AdjustForBackground" Mask="8" />
      <Flag Name="IsClipInsideMode" Mask="16" />
    </Field>
    <Field Name="Contrast" Code="281" Type="int16" DefaultValue="100" />
    <Field Name="Fade" Code="282" Type="int16" DefaultValue="0" />
    <Field Name="BoundaryPoints" Code="-1" Type="Point" DefaultValue="[]Point{}" AllowMultiples="true" />
    <Field Name="pointX" Code="11" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <Field Name="pointY" Code="21" Type="float64" DefaultValue="[]float64{}" AllowMultiples="true" />
    <WriteOrder>
      <WriteSpecificValue Code="100" Value='"AcDbUnderlayReference"' />
      <WriteField Field="ObjectHandle" />
      <WriteField Field="InsertionPoint" />
      <WriteField Field="XScale" />
      <WriteField Field="YScale" />
      <WriteField Field="ZScale" />
      <WriteField Field="RotationAngle" />
      <WriteField Field="Normal" />
      <WriteField Field="Flags" />
      <WriteField Field="Contrast" />
      <WriteField Field="Fade" />
      <Foreach Field="BoundaryPoints()">
        <WriteSpecificValue Code="11" Value="item.X" />
        <WriteSpecificValue Code="21" Value="item.Y" />
      </Foreach>
    </WriteOrder>
  </Interface>
  <Entity Name="DgnUnderlay" TypeString="DGNUNDERLAY" ImplementInterfaces="Entity,Underlay" />
  <Entity Name="DwfUnderlay" TypeString="DWFUNDERLAY" ImplementInterfaces="Entity,Underlay" />
  <Entity Name="PdfUnderlay" TypeString="PDFUNDERLAY" ImplementInterfaces="Entity,Underlay" />
  <!--

  VERTEX

  -->
  <Entity Name="Vertex" SubclassMarker="AcDbVertex" TypeString="VERTEX" GenerateWriter="false">
    <Field Name="Location" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="StartingWidth" Code="40" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="EndingWidth" Code="41" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Bulge" Code="42" Type="float64" DefaultValue="0.0" DisableWritingDefault="true" />
    <Field Name="Flags" Code="70" Type="int" DefaultValue="0" ReadConverter="int(%v)" WriteConverter="int16(%v)">
      <Flag Name="IsExtraCreatedByCurveFit" Mask="1" />
      <Flag Name="IsCurveFitTangentDefined" Mask="2" />
      <Flag Name="IsSplineVertexCreatedBySplineFitting" Mask="8" />
      <Flag Name="IsSplineFrameControlPoint" Mask="16" />
      <Flag Name="Is3DPolylineVertex" Mask="32" />
      <Flag Name="Is3DPolygonMesh" Mask="64" />
      <Flag Name="IsPolyfaceMeshVertex" Mask="128" />
    </Field>
    <Field Name="CurveFitTangentDirection" Code="50" Type="float64" DefaultValue="0.0" />
    <Field Name="PolyfaceMeshVertexIndex1" Code="71" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R13" />
    <Field Name="PolyfaceMeshVertexIndex2" Code="72" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R13" />
    <Field Name="PolyfaceMeshVertexIndex3" Code="73" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R13" />
    <Field Name="PolyfaceMeshVertexIndex4" Code="74" Type="int" DefaultValue="0" DisableWritingDefault="true" ReadConverter="int(%v)" WriteConverter="int16(%v)" MinVersion="R13" />
    <Field Name="Identifier" Code="91" Type="int" DefaultValue="0" MinVersion="R2010" />
  </Entity>
  <!--

  VIEWPORT

  -->
  <!-- TODO MinVersion="R12" -->
  <!--

  WIPEOUT

  -->
  <!-- inherits from IMAGE -->
  <Entity Name="Wipeout" TypeString="WIPEOUT" ImplementInterfaces="Entity,RasterImage" MinVersion="R2000" />
  <!--

  XLINE

  -->
  <Entity Name="XLine" SubclassMarker="AcDbXline" TypeString="XLINE" MinVersion="R13">
    <Field Name="FirstPoint" Code="10" Type="Point" DefaultValue="*NewOrigin()" CodeOverrides="10,20,30" />
    <Field Name="UnitDirectionVector" Code="11" Type="Vector" DefaultValue="*NewXAxis()" CodeOverrides="11,21,31" />
  </Entity>
</Specification>
